### ISSUE TITLE
Welcome message

### ISSUE THREAD

**Issue by tabuna** [pcherednichenko/spam_fighter_bot#2]
Thanks for the great bot. But the greeting message in English seems odd. More correct would be:

>Hi [username]l, welcome to the Laravel Orchid Chat! To make sure that you aren't a bot, please answer the following question by replying with the result as a number: [question]

What do you think about it?

**Comment by pcherednichenko** [comment]
Hi @tabuna ! Thank you for good suggestion, changes should be released within one hour
